---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Include overrides specific to Fedora.
  ansible.builtin.include_vars: Fedora.yml
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution == "Fedora"

# Setup/install tasks.
- name: Include setup for RedHat
  ansible.builtin.include_tasks: setup-redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Include setup for Debian
  ansible.builtin.include_tasks: setup-debian.yml
  when: ansible_os_family == 'Debian'

- name: Ensure directories to export exist
  ansible.builtin.file:  # noqa risky-file-permissions
    path: "{{ item.strip().split()[0] }}"
    state: directory
  with_items: "{{ nfs_exports }}"

- name: Copy exports file.
  ansible.builtin.template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: '0644'
  notify: Reload nfs

- name: Ensure nfs is running.
  ansible.builtin.service:
    name: "{{ nfs_server_daemon }}"
    state: started
    enabled: yes
  when: nfs_exports|length
